--- 
- name: install the openjdk 
  become: yes
  hosts: all
  vars:
    ubunt_java_name: openjdk-8-jdk
    centos_java_name: openjdk-11-jdk 
    state: present 
  tasks: 

   - name: install java in ubuntu 
     ansible.builtin.debug:
       msg: installing java 8 in ubuntu 
     when: 
      - ansible-facts["distribution"] == "ubuntu" 
   - name: installing openjdk in ubuntu
     ansible.builtin.apt:
       name: "{{ ubunt_java_name }}" 
       update_cache: yes
       state: "{{ state }}"
     when:
       - ansible-facts["distribution"] == "ubuntu" 
   - name: install java in ubuntu 
     ansible.builtin.debug:
       msg: installing java 
     when: 
      - ansible-facts["distribution"] == "centos"
   - name: 
     ansible.builtin.yum: 
       name: "{{ centos_java_name }}"
       update_cache: yes 
       state: "{{ state }}"
     when: 
       - ansible-facts["distribution"] == "centos"   
 