--- 
-name: tomcat9
become: yes
hosts: all
vars:
  package_name: openjdk-11-jdk
  user_name: system user
  home_dirctory: /opt/tomcat
  tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
  tomcat_url_dest: /tmp
  tomcat_download_src: /tmp/apache-tomcat-9.0.65.tar.gz
  tomcat_permission: /opt/tomcat/latest/bin/*.sh
tasks:
- name: print package name "{{ package_name }}"
  ansible.builtin.debug:
    msg: installing openjdk-11-jdk 
- name: installing java-11 
  ansible.builtin.apt:
    name: "{{ package_name }}"     
    state: present  
- name: creating user
  ansible.builtin.user:
    name: "{{ user_name }}"
    creat_home: yes
    home: "{{ home_dirctory }}"
    shell: /bin/false
- name: download the tomcat version 
  ansible.builtin.get_url:
    url: "{{ tomcat_url }}"
    dest: "{{ tomcat_url_dest }}"
  notify:
    - extract tomcat
- name: flush handlers
  meta: flush handlers 
- name: extract tomcat
  ansible.builtin.unarchive:
    src: "{{ tomcat_download_src }}"
    dest: "{{ home_dirctory }}"
    remote_src: yes     
- name: creat the symbolink  
  ansible.builtin.file:
    src: "{{ tomcat_download_src }}/apache-tomcat-9.0.65.tar.gz"
    dest: "{{ home_dirctory }}/latest"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link 
- name: permission for user 
  ansible.builtin.file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
- name: permission for user 
  ansible.builtin.file:
    path: "{{ tomcat_permission }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "+x"    
- name: copy the service file 
  ansible.builtin.copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    owner: "{{ user_name }}"
    group: "{{ user_name }}"     
    mode: '777' 
- name: demon-reload
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: tomcat.service 
- name: enable the tomcat.service 
  ansible.builtin.systemd:
    name: tomcat.service 
    enabled: yes  
                 

