--- 
- name: install the openjdk 
  become: yes
  hosts: all
  vars:
    ubunt_java_name: openjdk-8-jdk
    centos_java_name: java-11-openjdk-devel
  
  tasks: 
    - name: java installing 
      ansible.builtin.debug:
        msg: java 8 installing 
    - name: installing openjdk in ubuntu
      ansible.builtin.apt:
        name: "{{ ubunt_java_name }}" 
        update_cache: yes
        state: present 
    
